# Generated by Django 4.2.4 on 2023-08-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="referralcode",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
