# Generated by Django 4.2.4 on 2023-08-29 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_referralcode_points"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="referral",
            options={"ordering": ("-updated_at",)},
        ),
        migrations.AlterModelOptions(
            name="referralcode",
            options={"ordering": ("-updated_at",)},
        ),
        migrations.AddField(
            model_name="referral",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="referral",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="referralcode",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="referralcode",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
